<?php

/**
 * @file
 * Implements the hooks related to this module.
 */

use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

/**
 * Implments hook_views_query_alter()
 */
function views_practice_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'event_details') {
    $query->addOrderBy('node__field_date_of_event', 'field_date_of_event_value', 'ASC');
  }
}

/**
 * Implements hook_views_data_alter().
 */
function views_practice_views_data_alter(array &$data) {
  $data['node__field_type']['relationship_name'] = [
    'title' => t('Custom Relationship'),
    'help' => t('This is to add the event type relationship'),
    'relationship' => [
      'base' => 'taxonomy_term_field_data',
      'base field' => 'tid',
      'relationship field' => 'field_type_target_id',
      'id' => 'standard',
    ],
  ];
}
